import Topbar from "../Topbar";
import Navbar from "../Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="main-wrapper">
      <Topbar />
      <div className="h-full flex flex-1 pt-[54px] lg:pt-[96px]">
        <Navbar />
        {children}
      </div>
      <ToastContainer />
    </div>
  );
}
